In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
df_full= pd.read_csv("dataframe_SAA_clinico_V0.csv")
df_clin = pd.read_csv("dataframe_clinicos_BL.csv")

df_150 = df_full[df_full["SAAMethod"] == "Amprion-Alpha-synuclein-SAA"].copy()
df_150 = df_150[df_150["SAA_Status"] != "Inconclusive"] #Aqui he quitado todos los resultados de la variable respuesta que aparecen como inconclusivos ya que no nos aportan ningún tipo de información.
df_150 = df_150[df_150["SAA_Type"] != "Undetermined"] #Aquí he eliminado todos aquellos en los que el SAA_Type salía como undetermined debido a que cuando sale undetermined se repite.
df_150 = df_150[df_150["CLINICAL_EVENT"] == "BL"]

df_24 = df_full[df_full["SAAMethod"] == "Amprion-24h alpha-synuclein-SAA"].copy()
df_24 = df_24[df_24["SAA_Status"] != "Inconclusive"]
df_24 = df_24[df_24["SAA_Type"] != "Undetermined"]
df_24 = df_24[df_24["CLINICAL_EVENT"] == "BL"]

df_clin = df_clin[df_clin["CLINICAL_EVENT"] == "BL"]

C:\Users\david\AppData\Local\Temp\ipykernel_21040\3463510937.py:1: DtypeWarning: Columns (2,67) have mixed types. Specify dtype option on import or set low_memory=False.
  df_full= pd.read_csv("dataframe_SAA_clinico_V0.csv")

In [4]:
id_col = "PATNO"     # cambia si tu ID se llama distinto
visit_col = "CLINICAL_EVENT"  # cambia si tu visita se llama distinto
bl_value = "BL"      # cambia si baseline es otro código

pos_sex_150 = df_150.columns.get_loc("SEX")
saa_cols_150 = list(df_150.columns[pos_sex_150+1:])
df_150_saa = df_150[["PATNO"] + saa_cols_150].copy()

pos_sex_24 = df_24.columns.get_loc("SEX")
saa_cols_24 = list(df_24.columns[pos_sex_24+1:])
df_24_saa = df_24[["PATNO"] + saa_cols_24].copy()

In [5]:
df_clin_150 = df_clin.merge(
    df_150_saa,
    on=["PATNO"],
    how= "left"
)
df_clin_150 = df_clin_150.dropna(subset=["SAAMethod"])

df_clin_24 = df_clin.merge(
    df_24_saa,
    on=["PATNO"],
    how="left"
)
df_clin_24 = df_clin_24.dropna(subset=["SAAMethod"])



df_clin_24

,Unnamed: 0,PATNO,GUID,CLINICAL_EVENT,visit_month,age_at_baseline,sex,ethnicity,race,prodromal_category,study_arm,diagnosis,initial_diagnosis,most_recent_diagnosis,change_in_diagnosis,change_in_diagnosis_months_after_baseline,surgery_for_parkinson_disease,pd_diagnosis_months_after_baseline,age_at_diagnosis,pd_medication_initiation_months_after_baseline,pd_medication_start_months_after_baseline,use_of_pd_medication,pd_medication_recent_use_months_after_baseline,on_levodopa,on_dopamine_agonist,on_other_pd_medications,COHORT,TYPE,SAAMethod,SAA_Status,SAA_Type,Fmax_24h_Rep1,Fmax_24h_Rep2,Fmax_24h_Rep3,TTT_24h_Rep1,TTT_24h_Rep2,TTT_24h_Rep3,AUC_24h_Rep1,AUC_24h_Rep2,AUC_24h_Rep3,TSmax_24h_Rep1,TSmax_24h_Rep2,TSmax_24h_Rep3,SLOPEMax_24h_Rep1,SLOPEMax_24h_Rep2,SLOPEMax_24h_Rep3,Fmax_150h_Rep1,Fmax_150h_Rep2,Fmax_150h_Rep3,TTT_150h_Rep1,TTT_150h_Rep2,TTT_150h_Rep3,AUC_150h_Rep1,AUC_150h_Rep2,AUC_150h_Rep3,T50_150h_Rep1,T50_150h_Rep2,T50_150h_Rep3,SLOPE_150h_Rep1,SLOPE_150h_Rep2,SLOPE_150h_Rep3,InstrumentRep1,InstrumentRep2,InstrumentRep3,SampleVolRep1,SampleVolRep2,SampleVolRep3,RUNDATE,PROJECTID,PI_NAME,PI_INSTITUTION
3,31,75423,NIHAB458XTRR5,BL,-1.0,72.0,Male,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,No PD Nor Other Neurological Disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-24h alpha-synuclein-SAA,Negative,NaN,541.0,86000.0,549.0,NaN,13.65,NaN,3.625290e+06,2.595000e+09,4.519540e+06,9.76,14.26,4.50,0.02,18.76,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,2023-01-04,237.0,Luis Concha,Amprion
5,50,52634,NIHAD575RNPP2,BL,-1.0,55.0,Female,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,No PD Nor Other Neurological Disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-24h alpha-synuclein-SAA,Positive,Type1,155170.0,144502.0,137212.0,9.04,7.92,9.56,6.262000e+09,6.121000e+09,5.404000e+09,9.26,8.26,10.01,51.90,49.25,44.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,2023-01-04,237.0,Luis Concha,Amprion
18,138,59152,NIHAN814PBLDG,BL,-1.0,52.0,Female,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,No PD Nor Other Neurological Disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-24h alpha-synuclein-SAA,Negative,NaN,546.0,522.0,536.0,NaN,NaN,NaN,4.158680e+06,4.132150e+06,4.172660e+06,3.75,23.77,9.76,0.03,0.03,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,2023-01-04,237.0,Luis Concha,Amprion
50,312,58716,NIHBF621WLWB2,BL,-1.0,57.0,Female,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,No PD Nor Other Neurological Disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-24h alpha-synuclein-SAA,Positive,Type1,145778.0,152805.0,146914.0,10.12,6.80,14.59,5.291000e+09,6.471000e+09,3.790000e+09,10.51,7.26,15.01,49.92,51.39,50.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,2023-01-04,237.0,Luis Concha,Amprion
65,397,70652,NIHBR961UMLYP,BL,-1.0,71.0,Female,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,Essential Tremor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-24h alpha-synuclein-SAA,Positive,Type1,134358.0,133481.0,122672.0,8.68,11.64,9.01,5.544000e+09,4.572000e+09,5.012000e+09,9.01,12.01,9.26,45.00,45.00,38.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,2023-01-04,237.0,Luis Concha,Amprion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1968,14409,75485,NaN,BL,-1.0,63.0,Male,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,No PD Nor Other Neurological Disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-24h alpha-synuclein-SAA,Negative,NaN,614.0,550.0,556.0,NaN,NaN,NaN,3.065620e+06,4.433480e+06,3.173360e+06,17.02,4.00,15.01,0.02,0.02,0.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,2023-01-04,237.0,Luis Concha,Amprion
1969,14410,75496,NaN,BL,-1.0,82.0,Male,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,No PD Nor Other Neurological Disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-24h alpha-synuclein-SAA,Positive,Type1,144190.0,143706.0,150129.0,8.27,7.77,8.07,6.221000e+09,6.400000e+09,6.424000e+09,8.51,8.01,8.51,49.18,47.99,50.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,2023-01-04,237.0,Luis Concha,Amprion
1976,14455,90456,NaN,BL,-1.0,82.0,Male,Not Hispanic or Latino,White,Hyposmia,Prodromal,Prodromal non-motor PD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-24h alpha-synuclein-SAA,Negative,NaN,505.0,456.0,446.0,NaN,NaN,NaN,4.269350e+06,2.875860e+06,2.092520e+06,9.01,17.52,22.27,0.02,0.01,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,NaN,NaN,NaN,2023-01-04,237.0,Luis Concha,Amprion
1977,14471,91837,NaN,BL,-1.0,74.0,Male,Not Hispanic or Latino,White,Hyposmia,Prodromal,Prodromal non-motor PD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-24h alpha-synuclein-SAA,Negative,NaN,526.0,522.0,541.0,NaN,NaN,NaN,3.980300e+06,3.942780e+06,4.149440e+06,4.00,13.01,10.01,0.02,0.02,0.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,2023-01-04,237.0,Luis Concha,Amprion
1978,14473,92834,NaN,BL,-1.0,66.0,Male,Not Hispanic or Latino,White,Hyposmia,Prodromal,Prodromal non-motor PD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-24h alpha-synuclein-SAA,Positive,Type1,152048.0,123602.0,128129.0,7.77,7.82,7.81,6.319000e+09,5.306000e+09,5.186000e+09,8.01,8.26,8.26,49.70,40.44,41.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,NaN,NaN,NaN,2023-01-04,237.0,Luis Concha,Amprion

##### Para poder trabajar en R unicamente con la variable respuesta y los datos clínicos, vamos a borrar todas las variables posteriores a la variable respuesta y todas aquellas variables de diagnosis que no tienen valores en la baseline

In [ ]:
df_onlyclin_150 = df_clin_150.loc[:, :'SAA_Status']

df_onlyclin_150

,Unnamed: 0,PATNO,GUID,CLINICAL_EVENT,visit_month,age_at_baseline,sex,ethnicity,race,prodromal_category,study_arm,diagnosis,initial_diagnosis,most_recent_diagnosis,change_in_diagnosis,change_in_diagnosis_months_after_baseline,surgery_for_parkinson_disease,pd_diagnosis_months_after_baseline,age_at_diagnosis,pd_medication_initiation_months_after_baseline,pd_medication_start_months_after_baseline,use_of_pd_medication,pd_medication_recent_use_months_after_baseline,on_levodopa,on_dopamine_agonist,on_other_pd_medications,COHORT,TYPE,SAAMethod,SAA_Status
0,0,3433,NIHAA107VTGPE,BL,-1.0,82.0,Female,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,PD,Idiopathic PD,NaN,NaN,NaN,NaN,NaN,-3.0,82.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PD,Cerebrospinal Fluid,Amprion-Alpha-synuclein-SAA,Positive
1,17,56126,NIHAB015ZHNUR,BL,-1.0,56.0,Female,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,No PD Nor Other Neurological Disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-Alpha-synuclein-SAA,Negative
2,22,51971,NIHAB029GUMTG,BL,-1.0,66.0,Male,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort PD,Idiopathic PD,NaN,NaN,NaN,NaN,NaN,-24.0,64.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PD,Cerebrospinal Fluid,Amprion-Alpha-synuclein-SAA,Positive
4,34,4054,NIHAB501ZPZFM,BL,-1.0,62.0,Female,Not Hispanic or Latino,Black or African American,Unknown/Not collected as enrollment criterion,PD,Idiopathic PD,NaN,NaN,NaN,NaN,NaN,-2.5,62.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PD,Cerebrospinal Fluid,Amprion-Alpha-synuclein-SAA,Positive
6,54,3434,NIHAE587EYZGL,BL,-1.0,54.0,Male,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,PD,Idiopathic PD,NaN,NaN,NaN,NaN,NaN,-2.5,54.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PD,Cerebrospinal Fluid,Amprion-Alpha-synuclein-SAA,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1969,14410,75496,NaN,BL,-1.0,82.0,Male,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,No PD Nor Other Neurological Disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-Alpha-synuclein-SAA,Positive
1970,14413,75525,NaN,BL,-1.0,70.0,Female,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,No PD Nor Other Neurological Disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-Alpha-synuclein-SAA,Negative
1976,14455,90456,NaN,BL,-1.0,82.0,Male,Not Hispanic or Latino,White,Hyposmia,Prodromal,Prodromal non-motor PD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-Alpha-synuclein-SAA,Negative
1977,14471,91837,NaN,BL,-1.0,74.0,Male,Not Hispanic or Latino,White,Hyposmia,Prodromal,Prodromal non-motor PD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-Alpha-synuclein-SAA,Negative
1978,14473,92834,NaN,BL,-1.0,66.0,Male,Not Hispanic or Latino,White,Hyposmia,Prodromal,Prodromal non-motor PD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prodromal,Cerebrospinal Fluid,Amprion-Alpha-synuclein-SAA,Positive

In [14]:
df_onlyclin_150 = df_onlyclin_150.loc[:, ~df_onlyclin_150.columns.str.contains('_diagnosis', case=False)]
df_onlyclin_150 = df_onlyclin_150.loc[:, ~df_onlyclin_150.columns.str.contains('medication', case=False)]

df_onlyclin_150 = df_onlyclin_150.drop(columns=["surgery_for_parkinson_disease", "on_levodopa", "on_dopamine_agonist", "TYPE", "SAAMethod"])
df_onlyclin_150

KeyError: "['surgery_for_parkinson_disease', 'on_levodopa', 'on_dopamine_agonist', 'TYPE', 'SAAMethod'] not found in axis"

In [18]:
df_onlyclin_24 = df_clin_24.loc[:, :'SAA_Status']
df_onlyclin_24 = df_onlyclin_24.loc[:, ~df_onlyclin_24.columns.str.contains('_diagnosis', case=False)]
df_onlyclin_24 = df_onlyclin_24.loc[:, ~df_onlyclin_24.columns.str.contains('medication', case=False)]

df_onlyclin_24 = df_onlyclin_24.drop(columns=["surgery_for_parkinson_disease", "on_levodopa", "on_dopamine_agonist", "TYPE", "SAAMethod"])
df_onlyclin_24

,Unnamed: 0,PATNO,GUID,CLINICAL_EVENT,visit_month,age_at_baseline,sex,ethnicity,race,prodromal_category,study_arm,diagnosis,COHORT,SAA_Status
3,31,75423,NIHAB458XTRR5,BL,-1.0,72.0,Male,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,No PD Nor Other Neurological Disorder,Prodromal,Negative
5,50,52634,NIHAD575RNPP2,BL,-1.0,55.0,Female,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,No PD Nor Other Neurological Disorder,Prodromal,Positive
18,138,59152,NIHAN814PBLDG,BL,-1.0,52.0,Female,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,No PD Nor Other Neurological Disorder,Prodromal,Negative
50,312,58716,NIHBF621WLWB2,BL,-1.0,57.0,Female,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,No PD Nor Other Neurological Disorder,Prodromal,Positive
65,397,70652,NIHBR961UMLYP,BL,-1.0,71.0,Female,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,Essential Tremor,Prodromal,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1968,14409,75485,NaN,BL,-1.0,63.0,Male,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,No PD Nor Other Neurological Disorder,Prodromal,Negative
1969,14410,75496,NaN,BL,-1.0,82.0,Male,Not Hispanic or Latino,White,Unknown/Not collected as enrollment criterion,Genetic Cohort Unaffected,No PD Nor Other Neurological Disorder,Prodromal,Positive
1976,14455,90456,NaN,BL,-1.0,82.0,Male,Not Hispanic or Latino,White,Hyposmia,Prodromal,Prodromal non-motor PD,Prodromal,Negative
1977,14471,91837,NaN,BL,-1.0,74.0,Male,Not Hispanic or Latino,White,Hyposmia,Prodromal,Prodromal non-motor PD,Prodromal,Negative
1978,14473,92834,NaN,BL,-1.0,66.0,Male,Not Hispanic or Latino,White,Hyposmia,Prodromal,Prodromal non-motor PD,Prodromal,Positive

In [19]:
df_onlyclin_24.to_csv("df_asociacion_24.csv")
df_onlyclin_150.to_csv("df_asociacion_150.csv")