In [1]:
import pandas as pd

c:\Users\david\Desktop\master\TFM\Script

Cargamos los df correspondientes para 24 y 150 horas y eliminamos las columnas que no nos aporten información necesaria para el analisis

In [2]:
df_24 = pd.read_csv("data/df_24_mutaciones.csv")
df_150 = pd.read_csv("data/df_150_mutaciones.csv")
df_24 = df_24.drop(df_24.columns[[0,1,2,4,5,6,12,14,15]], axis=1)
df_150 = df_150.drop(df_150.columns[[0,1,2,4,5,6,12,14,15]], axis=1)

#df_24 = df_24.dropna()
#df_150 = df_150.dropna()

In [3]:
df_24

,PATNO,age_at_baseline,age_group,sex,ethnicity,race,study_arm,SAA_Status,has_known_GBA_mutation_in_WGS,has_known_LRRK2_mutation_in_WGS,has_known_SNCA_mutation_in_WGS,has_known_APOE_E4_mutation_in_WGS,has_known_PD_Mutation_in_WGS
0,10874,73.0,≥70,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes
1,12224,66.0,60-69,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes
2,12593,66.0,60-69,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes
3,13039,67.0,60-69,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No
4,13424,76.0,≥70,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,90456,82.0,≥70,Male,Not Hispanic or Latino,White,Prodromal,Negative,No,No,No,No,No
285,91097,67.0,60-69,Male,Hispanic or Latino,Unknown,Prodromal,Positive,No,No,No,Yes,Yes
286,91837,74.0,≥70,Male,Not Hispanic or Latino,White,Prodromal,Negative,No,No,No,No,No
287,92490,72.0,≥70,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No
288,92834,66.0,60-69,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes

Ahora seleccionamos del dataset que contiene MDS-UPDRS-III score solo aquellos individuos correspondientes a ppmi y nos quedamos solo con la BL de cada paciente

In [4]:
df_MDS = pd.read_csv("data/Dataset MDS-UPDRS-III score.csv")

df_MDS = df_MDS[df_MDS["participant_id"].str.startswith("PP-")]
df_MDS = df_MDS[df_MDS["visit_name"].str.startswith("SC")] # Selecciono solo la visita BL (en este df se llama SC)

df_MDS = df_MDS.rename(columns={"participant_id": "PATNO"})

df_MDS

,PATNO,GUID,visit_name,visit_month,code_upd2301_speech_problems,code_upd2302_facial_expression,code_upd2303a_rigidity_neck,code_upd2303b_rigidity_rt_upper_extremity,code_upd2303c_rigidity_left_upper_extremity,code_upd2303d_rigidity_rt_lower_extremity,...,upd2317d_rest_tremor_amplitude_left_lower_extremity,upd2317e_rest_tremor_amplitude_lip_or_jaw,upd2318_consistency_of_rest_tremor,upd2da_dyskinesias_during_exam,upd2db_movements_interfere_with_ratings,code_upd2hy_hoehn_and_yahr_stage,upd2hy_hoehn_and_yahr_stage,upd23a_medication_for_pd,upd23b_clinical_state_on_medication,mds_updrs_part_iii_summary_score
6031,PP-10874,NaN,SC,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Normal,Normal,Normal,No,NaN,0.0,Stage 0,No,NaN,2.0
6056,PP-12499,NaN,SC,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Normal,Normal,Normal,No,NaN,0.0,Stage 0,No,NaN,0.0
6070,PP-12593,NaN,SC,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Normal,Normal,Normal,No,NaN,0.0,Stage 0,No,NaN,2.0
6084,PP-13039,NIHLU969RYBRK,SC,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Normal,Normal,Normal,No,NaN,0.0,Stage 0,No,NaN,0.0
6096,PP-13424,NaN,SC,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Normal,Normal,Normal,No,NaN,0.0,Stage 0,No,NaN,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23472,PP-70658,NIHUJ988MBKUF,SC,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Normal,Normal,Normal,No,NaN,0.0,Stage 0,No,NaN,0.0
23474,PP-40067,NIHND555HJJED,SC,-1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,Normal,Normal,Normal,No,NaN,0.0,Stage 0,No,NaN,1.0
23498,PP-41299,NaN,SC,-1.0,1.0,1.0,0.0,1.0,0.0,1.0,...,Slight,Normal,Slight,Yes,No,3.0,Stage 3,No,NaN,35.0
23509,PP-3175,NIHFG006HTWYT,SC,-1.0,0.0,1.0,0.0,0.0,2.0,0.0,...,Normal,Normal,Moderate,No,NaN,1.0,Stage 1,No,NaN,17.0
23515,PP-3782,NaN,SC,-1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,Normal,Normal,Slight,No,NaN,2.0,Stage 2,No,NaN,10.0

In [5]:
#Nos quedamos con la ultima columna del df que es lo unico que necesitamos

df_MDS = df_MDS[["PATNO", "visit_name", "mds_updrs_part_iii_summary_score"]]

df_MDS

          PATNO visit_name  mds_updrs_part_iii_summary_score
6031   PP-10874         SC                               2.0
6056   PP-12499         SC                               0.0
6070   PP-12593         SC                               2.0
6084   PP-13039         SC                               0.0
6096   PP-13424         SC                               4.0
...         ...        ...                               ...
23472  PP-70658         SC                               0.0
23474  PP-40067         SC                               1.0
23498  PP-41299         SC                              35.0
23509   PP-3175         SC                              17.0
23515   PP-3782         SC                              10.0

[1005 rows x 3 columns]

Hacemos lo mismo para el resto de valores necesarios para la tabla

In [6]:
df_HY = pd.read_csv("data/Dataset MDS-UPDRS-III score.csv")

df_HY = df_HY[df_HY["participant_id"].str.startswith("PP-")]
df_HY = df_HY[df_HY["visit_name"].str.startswith("SC")] # Selecciono solo la visita BL (en este df se llama SC)

df_HY = df_HY.rename(columns={"participant_id": "PATNO"})
df_HY = df_HY[["PATNO", "visit_name", "code_upd2hy_hoehn_and_yahr_stage"]]


df_HY

          PATNO visit_name  code_upd2hy_hoehn_and_yahr_stage
6031   PP-10874         SC                               0.0
6056   PP-12499         SC                               0.0
6070   PP-12593         SC                               0.0
6084   PP-13039         SC                               0.0
6096   PP-13424         SC                               0.0
...         ...        ...                               ...
23472  PP-70658         SC                               0.0
23474  PP-40067         SC                               0.0
23498  PP-41299         SC                               3.0
23509   PP-3175         SC                               1.0
23515   PP-3782         SC                               2.0

[1005 rows x 3 columns]

In [7]:
df_moca = pd.read_csv("data/df_MoCa_Score.csv")

df_moca = df_moca[df_moca["participant_id"].str.startswith("PP-")]
df_moca = df_moca[df_moca["visit_name"].str.startswith("SC")] # Selecciono solo la visita BL (en este df se llama SC)

df_moca = df_moca.rename(columns={"participant_id": "PATNO"})

#Nos quedamos con la ultima columna del df que es lo unico que necesitamos

df_moca = df_moca[["PATNO", "visit_name", "moca_total_score"]]

df_moca

          PATNO visit_name  moca_total_score
4479   PP-10874         SC              27.0
4486   PP-12224         SC              27.0
4491   PP-12499         SC              26.0
4498   PP-12593         SC              28.0
4504   PP-13039         SC              26.0
...         ...        ...               ...
13657  PP-74199         SC              25.0
13660  PP-74763         SC              28.0
13666   PP-3175         SC              28.0
13668   PP-3782         SC              23.0
13669  PP-41299         SC              27.0

[1542 rows x 3 columns]

Hacemos merge entre los 3 nuevos datasets para crear uno solo que unir posteriormente a nuestros datasets de 24 y 150 horas con lo que podremos crear la tabla

In [8]:
df_merge = df_MDS.merge(
    df_HY,
    on=["PATNO", "visit_name"],
    how="left"
)

In [9]:
df_merge = df_merge.merge(
    df_moca,
    on=["PATNO", "visit_name"],
    how="outer"
)

In [10]:
#Como hay varios pacientes en los que tenemos dos baselines, nos vamos a quedar con la segunda en caso de que estén repetidos

df_merge = (
    df_merge.assign(
        prioridad=df_merge["visit_name"].map({"SC#2": 2, "SC": 1}).fillna(0)
    )
    .sort_values(["PATNO", "prioridad"], ascending=[True, False])
    .drop_duplicates(subset="PATNO", keep="first")
    .drop(columns="prioridad")
)

In [11]:
df_merge = df_merge.rename(columns={"visit_name": "CLINICAL_EVENT"})
df_merge["CLINICAL_EVENT"] = df_merge["CLINICAL_EVENT"].str.replace("SC", "BL")
df_merge["PATNO"] = df_merge["PATNO"].str.replace("PP-", "").astype(int)

df_merge

,PATNO,CLINICAL_EVENT,mds_updrs_part_iii_summary_score,code_upd2hy_hoehn_and_yahr_stage,moca_total_score
0,10874,BL,2.0,0.0,27.0
1,12224,BL,NaN,NaN,27.0
2,12499,BL,0.0,0.0,26.0
3,12593,BL,2.0,0.0,28.0
4,13039,BL,0.0,0.0,26.0
...,...,...,...,...,...
1543,90456,BL,4.0,0.0,24.0
1544,91097,BL,0.0,0.0,29.0
1545,91837,BL,2.0,0.0,26.0
1546,92490,BL,0.0,0.0,28.0
1547,92834,BL,0.0,0.0,29.0

ahora vamos a hacer merge con nuestros df de 24 y 150 horas

In [12]:
df_24_tabla = df_24.merge(
    df_merge,
    on = "PATNO",
    how = "left"
)

df_150_tabla = df_150.merge(
    df_merge,
    on = "PATNO",
    how = "left"
)

In [13]:
df_150_tabla.to_csv("df_150_tabla.csv")
df_24_tabla.to_csv("df_24_tabla.csv")

In [14]:
df_24_tabla.dropna()

,PATNO,age_at_baseline,age_group,sex,ethnicity,race,study_arm,SAA_Status,has_known_GBA_mutation_in_WGS,has_known_LRRK2_mutation_in_WGS,has_known_SNCA_mutation_in_WGS,has_known_APOE_E4_mutation_in_WGS,has_known_PD_Mutation_in_WGS,CLINICAL_EVENT,mds_updrs_part_iii_summary_score,code_upd2hy_hoehn_and_yahr_stage,moca_total_score
0,10874,73.0,≥70,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,BL,2.0,0.0,27.0
2,12593,66.0,60-69,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,BL,2.0,0.0,28.0
3,13039,67.0,60-69,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,BL,0.0,0.0,26.0
4,13424,76.0,≥70,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,BL,4.0,0.0,25.0
5,14281,62.0,60-69,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,BL,2.0,0.0,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,90456,82.0,≥70,Male,Not Hispanic or Latino,White,Prodromal,Negative,No,No,No,No,No,BL,4.0,0.0,24.0
285,91097,67.0,60-69,Male,Hispanic or Latino,Unknown,Prodromal,Positive,No,No,No,Yes,Yes,BL,0.0,0.0,29.0
286,91837,74.0,≥70,Male,Not Hispanic or Latino,White,Prodromal,Negative,No,No,No,No,No,BL,2.0,0.0,26.0
287,92490,72.0,≥70,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,BL,0.0,0.0,28.0
288,92834,66.0,60-69,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,BL,0.0,0.0,29.0