In [1]:
import pandas as pd

In [16]:
df_150 = pd.read_csv("df_150_tabla.csv")
df_24 = pd.read_csv("df_24_tabla.csv")

In [ ]:


df_150 = df_150[df_150["study_arm"] != "SWEDD"]
df_24  = df_24[df_24["study_arm"] != "SWEDD"]

df_24[df_24["CLINICAL_EVENT"] != "BL"]

Empty DataFrame
Columns: [Unnamed: 0, PATNO, age_at_baseline, age_group, sex, ethnicity, race, study_arm, SAA_Status, has_known_GBA_mutation_in_WGS, has_known_LRRK2_mutation_in_WGS, has_known_SNCA_mutation_in_WGS, has_known_APOE_E4_mutation_in_WGS, has_known_PD_Mutation_in_WGS, CLINICAL_EVENT, mds_updrs_part_iii_summary_score, code_upd2hy_hoehn_and_yahr_stage, moca_total_score]
Index: []

In [3]:
bins = [0, 50, 60, 70, 80, float("inf")]
labels = ["<50", "50-59", "60-69", "70-79", ">=80"]
df_150["age_group"] = pd.cut(df_150["age_at_baseline"], bins=bins, labels=labels, right=False)
df_24["age_group"] = pd.cut(df_24["age_at_baseline"], bins=bins, labels=labels, right=False)

In [4]:
df_150 = df_150.dropna(subset=["CLINICAL_EVENT"])
df_24 = df_24.dropna(subset=["CLINICAL_EVENT"])
df_24

,Unnamed: 0,PATNO,age_at_baseline,age_group,sex,ethnicity,race,study_arm,SAA_Status,has_known_GBA_mutation_in_WGS,has_known_LRRK2_mutation_in_WGS,has_known_SNCA_mutation_in_WGS,has_known_APOE_E4_mutation_in_WGS,has_known_PD_Mutation_in_WGS,CLINICAL_EVENT,mds_updrs_part_iii_summary_score,code_upd2hy_hoehn_and_yahr_stage,moca_total_score
0,0,10874,73.0,70-79,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,BL,2.0,0.0,27.0
1,1,12224,66.0,60-69,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,BL,NaN,NaN,27.0
2,2,12593,66.0,60-69,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,BL,2.0,0.0,28.0
3,3,13039,67.0,60-69,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,BL,0.0,0.0,26.0
4,4,13424,76.0,70-79,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,BL,4.0,0.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,284,90456,82.0,>=80,Male,Not Hispanic or Latino,White,Prodromal,Negative,No,No,No,No,No,BL,4.0,0.0,24.0
285,285,91097,67.0,60-69,Male,Hispanic or Latino,Unknown,Prodromal,Positive,No,No,No,Yes,Yes,BL,0.0,0.0,29.0
286,286,91837,74.0,70-79,Male,Not Hispanic or Latino,White,Prodromal,Negative,No,No,No,No,No,BL,2.0,0.0,26.0
287,287,92490,72.0,70-79,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,BL,0.0,0.0,28.0
288,288,92834,66.0,60-69,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,BL,0.0,0.0,29.0

In [5]:
df_24.columns

Index(['Unnamed: 0', 'PATNO', 'age_at_baseline', 'age_group', 'sex',
       'ethnicity', 'race', 'study_arm', 'SAA_Status',
       'has_known_GBA_mutation_in_WGS', 'has_known_LRRK2_mutation_in_WGS',
       'has_known_SNCA_mutation_in_WGS', 'has_known_APOE_E4_mutation_in_WGS',
       'has_known_PD_Mutation_in_WGS', 'CLINICAL_EVENT',
       'mds_updrs_part_iii_summary_score', 'code_upd2hy_hoehn_and_yahr_stage',
       'moca_total_score'],
      dtype='object')

In [6]:
bl24 = df_24.pop("CLINICAL_EVENT")
bl150 = df_150.pop("CLINICAL_EVENT")
df_24.insert(2, "CLINICAL_EVENT", bl24)
df_150.insert(2, "CLINICAL_EVENT", bl150)

df_150

,Unnamed: 0,PATNO,CLINICAL_EVENT,age_at_baseline,age_group,sex,ethnicity,race,study_arm,SAA_Status,has_known_GBA_mutation_in_WGS,has_known_LRRK2_mutation_in_WGS,has_known_SNCA_mutation_in_WGS,has_known_APOE_E4_mutation_in_WGS,has_known_PD_Mutation_in_WGS,mds_updrs_part_iii_summary_score,code_upd2hy_hoehn_and_yahr_stage,moca_total_score
0,0,10874,BL,73.0,70-79,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,2.0,0.0,27.0
1,1,12224,BL,66.0,60-69,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,NaN,NaN,27.0
2,2,12593,BL,66.0,60-69,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,2.0,0.0,28.0
3,3,13039,BL,67.0,60-69,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,0.0,0.0,26.0
4,4,13424,BL,76.0,70-79,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,4.0,0.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113,1113,90456,BL,82.0,>=80,Male,Not Hispanic or Latino,White,Prodromal,Negative,No,No,No,No,No,4.0,0.0,24.0
1114,1114,91097,BL,67.0,60-69,Male,Hispanic or Latino,Unknown,Prodromal,Positive,No,No,No,Yes,Yes,0.0,0.0,29.0
1115,1115,91837,BL,74.0,70-79,Male,Not Hispanic or Latino,White,Prodromal,Negative,No,No,No,No,No,2.0,0.0,26.0
1116,1116,92490,BL,72.0,70-79,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,0.0,0.0,28.0
1117,1117,92834,BL,66.0,60-69,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,0.0,0.0,29.0

In [7]:
df_150

,Unnamed: 0,PATNO,CLINICAL_EVENT,age_at_baseline,age_group,sex,ethnicity,race,study_arm,SAA_Status,has_known_GBA_mutation_in_WGS,has_known_LRRK2_mutation_in_WGS,has_known_SNCA_mutation_in_WGS,has_known_APOE_E4_mutation_in_WGS,has_known_PD_Mutation_in_WGS,mds_updrs_part_iii_summary_score,code_upd2hy_hoehn_and_yahr_stage,moca_total_score
0,0,10874,BL,73.0,70-79,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,2.0,0.0,27.0
1,1,12224,BL,66.0,60-69,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,NaN,NaN,27.0
2,2,12593,BL,66.0,60-69,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,2.0,0.0,28.0
3,3,13039,BL,67.0,60-69,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,0.0,0.0,26.0
4,4,13424,BL,76.0,70-79,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,4.0,0.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113,1113,90456,BL,82.0,>=80,Male,Not Hispanic or Latino,White,Prodromal,Negative,No,No,No,No,No,4.0,0.0,24.0
1114,1114,91097,BL,67.0,60-69,Male,Hispanic or Latino,Unknown,Prodromal,Positive,No,No,No,Yes,Yes,0.0,0.0,29.0
1115,1115,91837,BL,74.0,70-79,Male,Not Hispanic or Latino,White,Prodromal,Negative,No,No,No,No,No,2.0,0.0,26.0
1116,1116,92490,BL,72.0,70-79,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,0.0,0.0,28.0
1117,1117,92834,BL,66.0,60-69,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,0.0,0.0,29.0

In [8]:

df_junto = pd.concat([df_150, df_24], ignore_index=True)

df_junto

,Unnamed: 0,PATNO,CLINICAL_EVENT,age_at_baseline,age_group,sex,ethnicity,race,study_arm,SAA_Status,has_known_GBA_mutation_in_WGS,has_known_LRRK2_mutation_in_WGS,has_known_SNCA_mutation_in_WGS,has_known_APOE_E4_mutation_in_WGS,has_known_PD_Mutation_in_WGS,mds_updrs_part_iii_summary_score,code_upd2hy_hoehn_and_yahr_stage,moca_total_score
0,0,10874,BL,73.0,70-79,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,2.0,0.0,27.0
1,1,12224,BL,66.0,60-69,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,NaN,NaN,27.0
2,2,12593,BL,66.0,60-69,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,2.0,0.0,28.0
3,3,13039,BL,67.0,60-69,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,0.0,0.0,26.0
4,4,13424,BL,76.0,70-79,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,4.0,0.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1340,284,90456,BL,82.0,>=80,Male,Not Hispanic or Latino,White,Prodromal,Negative,No,No,No,No,No,4.0,0.0,24.0
1341,285,91097,BL,67.0,60-69,Male,Hispanic or Latino,Unknown,Prodromal,Positive,No,No,No,Yes,Yes,0.0,0.0,29.0
1342,286,91837,BL,74.0,70-79,Male,Not Hispanic or Latino,White,Prodromal,Negative,No,No,No,No,No,2.0,0.0,26.0
1343,287,92490,BL,72.0,70-79,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,0.0,0.0,28.0
1344,288,92834,BL,66.0,60-69,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,0.0,0.0,29.0

In [9]:
df_junto = df_junto.dropna(subset=["CLINICAL_EVENT"])

df_junto = df_junto.copy()
df_junto["CLINICAL_EVENT"] = df_junto["CLINICAL_EVENT"].replace("BL#2", "BL")

In [10]:
df_junto

,Unnamed: 0,PATNO,CLINICAL_EVENT,age_at_baseline,age_group,sex,ethnicity,race,study_arm,SAA_Status,has_known_GBA_mutation_in_WGS,has_known_LRRK2_mutation_in_WGS,has_known_SNCA_mutation_in_WGS,has_known_APOE_E4_mutation_in_WGS,has_known_PD_Mutation_in_WGS,mds_updrs_part_iii_summary_score,code_upd2hy_hoehn_and_yahr_stage,moca_total_score
0,0,10874,BL,73.0,70-79,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,2.0,0.0,27.0
1,1,12224,BL,66.0,60-69,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,NaN,NaN,27.0
2,2,12593,BL,66.0,60-69,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,2.0,0.0,28.0
3,3,13039,BL,67.0,60-69,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,0.0,0.0,26.0
4,4,13424,BL,76.0,70-79,Female,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,4.0,0.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1340,284,90456,BL,82.0,>=80,Male,Not Hispanic or Latino,White,Prodromal,Negative,No,No,No,No,No,4.0,0.0,24.0
1341,285,91097,BL,67.0,60-69,Male,Hispanic or Latino,Unknown,Prodromal,Positive,No,No,No,Yes,Yes,0.0,0.0,29.0
1342,286,91837,BL,74.0,70-79,Male,Not Hispanic or Latino,White,Prodromal,Negative,No,No,No,No,No,2.0,0.0,26.0
1343,287,92490,BL,72.0,70-79,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,No,No,0.0,0.0,28.0
1344,288,92834,BL,66.0,60-69,Male,Not Hispanic or Latino,White,Prodromal,Positive,No,No,No,Yes,Yes,0.0,0.0,29.0

In [11]:
df_150[
    (df_150["has_known_GBA_mutation_in_WGS"] == "Yes") &
    (df_150["study_arm"] == "Healthy Control")
]

,Unnamed: 0,PATNO,CLINICAL_EVENT,age_at_baseline,age_group,sex,ethnicity,race,study_arm,SAA_Status,has_known_GBA_mutation_in_WGS,has_known_LRRK2_mutation_in_WGS,has_known_SNCA_mutation_in_WGS,has_known_APOE_E4_mutation_in_WGS,has_known_PD_Mutation_in_WGS,mds_updrs_part_iii_summary_score,code_upd2hy_hoehn_and_yahr_stage,moca_total_score
41,41,3055,BL,68.0,60-69,Female,Not Hispanic or Latino,White,Healthy Control,Negative,Yes,No,No,Yes,Yes,NaN,NaN,28.0
121,121,3191,BL,66.0,60-69,Female,Not Hispanic or Latino,Multiracial,Healthy Control,Negative,Yes,No,No,Yes,Yes,NaN,NaN,29.0
165,165,3276,BL,55.0,50-59,Female,Not Hispanic or Latino,White,Healthy Control,Negative,Yes,No,No,No,Yes,NaN,NaN,28.0
180,180,3310,BL,64.0,60-69,Male,Not Hispanic or Latino,White,Healthy Control,Positive,Yes,No,No,Yes,Yes,NaN,NaN,27.0
210,210,3362,BL,42.0,<50,Female,Not Hispanic or Latino,White,Healthy Control,Negative,Yes,No,No,No,Yes,NaN,NaN,30.0
410,410,3768,BL,59.0,50-59,Male,Not Hispanic or Latino,White,Healthy Control,Negative,Yes,No,No,No,Yes,NaN,NaN,28.0

In [14]:
df_150.columns

Index(['Unnamed: 0', 'PATNO', 'CLINICAL_EVENT', 'age_at_baseline', 'age_group',
       'sex', 'ethnicity', 'race', 'study_arm', 'SAA_Status',
       'has_known_GBA_mutation_in_WGS', 'has_known_LRRK2_mutation_in_WGS',
       'has_known_SNCA_mutation_in_WGS', 'has_known_APOE_E4_mutation_in_WGS',
       'has_known_PD_Mutation_in_WGS', 'mds_updrs_part_iii_summary_score',
       'code_upd2hy_hoehn_and_yahr_stage', 'moca_total_score'],
      dtype='object')

In [ ]:
df_150["age_group"] = df_150["age_group"].replace({">=80": "≥80"})
df_150["age_group"] = df_150["age_group"].replace({">=80": "≥80"})

In [12]:
df_150.to_csv("df_150_tabla.csv")
df_24.to_csv("df_24_tabla.csv")
df_junto.to_csv("df_24y150h.csv")